# Generated by Django 4.1.1 on 2022-10-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="duration",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
