# Generated by Django 4.1.1 on 2022-10-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_course_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course", name="file", field=models.FileField(upload_to=""),
        ),
    ]
